---
language: ruby
rvm:
  - 2.1.5
  - 1.9.3-p551
before_script: "if [[ $TRAVIS_RUBY_VERSION != '1.9.3-p551' || $TRAVIS_SECURE_ENV_VARS != 'true' ]]; then unset CODECLIMATE_REPO_TOKEN; fi"
install: bundle install --deployment --without debug
notifications:
  webhooks:
    urls:
      - http://build-monitor.cfapps.io/projects/JBBP/webhook
    on_start: true
env:
  global:
    secure: aspFvi7Tr+tAFayZdqeWWCD/enk84Aspsv8SBl3VBEY4yKJw89X/sz50CiVFVxMQc4pyfZf5773apCWoLlCoTp49/GspKANeCa+4Uox2lh9qR6eF87s+pTrBzT6TqP6Hs2N/0Bq5L0DuuUPq7cB0zKo9Kuoi54hcPZYDzQbthys= #CODECLIMATE_REPO_TOKEN
